remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Teach Like Us]
description: [We are "open sourcing" content of a few of our courses and labs for others to "Teach Like Us". Trainers can then use these to deliver training within their Organizations and direct users to use these free labs on our platform.]
